### ISSUE TITLE
Video support progress tracker

### ISSUE THREAD

**Issue by cpvannier** [pixano/pixano#162]
- [x] #161
- [x] #165
- [ ] Add support for video annotation in item workspace
- [ ] Add support for video files in Pixano datasets
- [ ] Add support for video annotations in Pixano datasets
- [ ] Add importers for video datasets

**Comment by cpvannier** [comment]
Initial video support completed by #185, and later improved by #248, #253, #258, #268 and #278
