### ISSUE TITLE
3D support progress tracker

### ISSUE THREAD

**Issue by cpvannier** [pixano/pixano#163]
- [x] #161
- [ ] Add support for 3D visualization in item workspace
- [ ] Add support for 3D annotation in item workspace
- [ ] Add support for 3D files in Pixano datasets
- [ ] Add support for 3D annotations in Pixano datasets
- [ ] Add importers for 3D datasets

**Comment by cpvannier** [comment]
Obsolete
